// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_E8xOd9ONL-I6CrjRivPGLGl_PZ0-i1M',
    appId: '1:956748003566:web:7198699ac11487b7eddbff',
    messagingSenderId: '956748003566',
    projectId: 'studentportify-f9ab5',
    authDomain: 'studentportify-f9ab5.firebaseapp.com',
    storageBucket: 'studentportify-f9ab5.appspot.com',
    measurementId: 'G-XQ9S88MWH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAawCWtla_Dc0NH1awMCzipgsOnWcOQUfQ',
    appId: '1:956748003566:android:fac256f98bb2e427eddbff',
    messagingSenderId: '956748003566',
    projectId: 'studentportify-f9ab5',
    storageBucket: 'studentportify-f9ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMgof0NORrg-qvmoQQGAITpEoECqtrF70',
    appId: '1:956748003566:ios:06f981262325b45beddbff',
    messagingSenderId: '956748003566',
    projectId: 'studentportify-f9ab5',
    storageBucket: 'studentportify-f9ab5.appspot.com',
    iosBundleId: 'com.example.studentPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMgof0NORrg-qvmoQQGAITpEoECqtrF70',
    appId: '1:956748003566:ios:ac019a013fdc6a42eddbff',
    messagingSenderId: '956748003566',
    projectId: 'studentportify-f9ab5',
    storageBucket: 'studentportify-f9ab5.appspot.com',
    iosBundleId: 'com.example.studentPortfolio.RunnerTests',
  );
}
